<!DOCTYPE html>
<html lang="ko">
  <head>
    <title>이벤트루프</title>
    <script>
      // // 1) Promise인 fetch가 마이크로큐에 들어가고 try는 정상 종료. aaa 함수도 정상 종료.
      // // 2) 마이크로큐에 있던 fetch가 콜스택으로 돌아왔을 때 try-catch는 아까 정상 종료되었으므로 실패해도 못잡음
      const onClickLoop = () => {
        // const aaa = () => {
        //   try {
        //     fetch("https://qqqqq.com");
        //     console.log("철수"); // 로그까지 찍고, aaa 함수 정상 종료
        //   } catch (error) {
        //     console.log("에러가 발생하였습니다!");
        //   }
        // };
        // aaa();

        // 1) Promise인 fetch가 마이크로큐에 들어감. aaa함수도 await를 만나서 마이크로큐에 들어감.
        // 2) 마이크로큐에 있던 fetch가 콜스택으로 돌아왔을 때 try-catch가 포함된 aaa 함수도 다음 마이크로큐에서 대기중이므로 실패하면 잡힘
        const bbb = async () => {
          try {
            await fetch("https://qqqqq.com");
            console.log("철수");
          } catch (error) {
            console.log("에러가 발생하였습니다!");
          }
        };
        bbb();
      };
    </script>
  </head>
  <body>
    <button onclick="onClickLoop()">시작하기</button>
  </body>
</html>
